name: CICD - ACR - Pyramid

on:
  schedule:
    - cron: "0 0 * * SUN"
  push:
    branches:
      - "**"
    tags:
      - "v*"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
          
jobs:
  cicd_acr:
    uses: VanOord/datalab-github-actions/.github/workflows/cicd-acr-pyramid.yml@ruff
    with:
      tag: {{cookiecutter.project_repo}}
      namespace: {{cookiecutter.project_name}}
    secrets: inherit
